backend:
  name: github
  repo: xtradmk/interesting-america-hp
  branch: main
  base_url: https://ia-cms-oauth.<your-subdomain>.workers.dev
  auth_endpoint: auth

site_url: "https://xtradmk.github.io/interesting-america-hp/"
display_url: "https://xtradmk.github.io/interesting-america-hp/"
logo_url: "/interesting-america-hp/images/logo.svg"

media_folder: "src/images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow
