backend:
  name: github
  repo: xtradmk/interesting-america-hp
  branch: main
  base_url: https://ia-cms-oauth.<your-subdomain>.workers.dev
  auth_endpoint: auth

site_url: "https://interesting-america.com/"
display_url: "https://interesting-america.com/"
logo_url: "/images/logo.svg"

media_folder: "src/images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow
